#!/usr/bin/python3
# -*- coding: utf-8 -*-
###############################>GENERAL-INFORMATIONS<###############################
"""
Build in Python 3.6.5+

Author:
Filipe Dezordi
zimmer.filipe@gmail.com
https://dezordi.github.io/

Script repository:
https://github.com/dezordi/PEVEI
"""
###############################>LIBRARIES<###############################
import pandas as pd
import argparse, re
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.style as style
###############################>ARGUMENTS<###############################
parser = argparse.ArgumentParser(description = 'Create stacked barplot file for each assembly present in a concatenated taxonomy file')
parser.add_argument("-in", "--input", help="Concatenated file from more than 1 .tax file generated by PEVEI.py", required=True)
parser.add_argument("-md","--mode",help="Create plots with family or order taxonomy? default=Family",default='Family', choices=['Family','Order'])
parser.add_argument("-st","--specifictax",help="Pass specific taxon to generate plots, e.g. Rhabdoviridae Flaviviridae",nargs='+')
parser.add_argument("-gt","--groupbytax",help="Pass treshold number do group taxons, default = 5", default=5,type=int)
args = parser.parse_args()
input_file = args.input
plot_mode = args.mode
specific_tax = args.specifictax
group_value = args.groupbytax
###############################>SNS-STYLE<###############################
sns.set()
style.use('seaborn-poster')
sns.set_palette("husl", 9)
###############################>REGEX-FUNC<##############################
def get_prefix(name):
    return re.sub(r'\/.*','',name)
###############################>DATAFRAME<###############################
df = pd.read_csv(input_file, sep='\t',header = 0)
if specific_tax != None:
    df = df.loc[df['Family'].isin(specific_tax)]
#grouping families with less than 5 elements to 'Others'
family_count = df[plot_mode].value_counts()
family_low = family_count[family_count <= group_value]
family_low_list = family_low.index
for i in family_low_list:
    df[plot_mode] = df[plot_mode].replace({i:'Others'})
df.insert(0,'Genome',df['Element-ID'])
df['Genome'] = df['Genome'].apply(get_prefix)
df2 = df.groupby(["Genome", plot_mode]).size().reset_index(name="Count")
df3 = df2.pivot_table('Count', ['Genome'], plot_mode)
try:
    df3.drop(['Element-ID'], inplace=True)
    df3.drop([plot_mode], axis=1,inplace=True)
except:
    pass
labels = []
columns = [df3.columns.values.tolist()]
for list_ in columns:
    for i in list_:
        labels.append(i)
assemblies = ["Cx_qui_J2","Cx_tar_K1","Ae_aeg_Aag2","Ae_aeg_L5","Ae_aeg_BV","Ae_alb_Canu","Ae_alb_F1","Ae_alb_F2","Ae_alb_R1","An_fun_F3","An_fun_Fv1","An_sin_C2","An_sin_S2","An_cul_A1","An_min_M1","An_epi_E1","An_mac_BtQ1","An_mac_M1","An_atr_E3","An_nil_1","An_ste_5v2","An_ste_UCI","An_ste_S1","An_ste_7v2","An_ste_Astel2","An_chr_AchrA1","An_dar_C3","An_aqua_v1","An_alb_S2","An_dir_W1","An_cra_4v1","An_pun_5v1","An_kol_7v1","An_far_F2","An_far_wgs1","An_mer_M2","An_mel_C2","An_qua_S1","An_bwa_2","An_fon_9v1","An_ara_D1","An_col_M1","An_col_Ng","An_gam_s1","An_gam_p4","An_gam_pims","An_gam_BV"]
df3 = df3.reindex(assemblies)
barplot = df3.plot(kind="bar", stacked=True, edgecolor='black', width=1)
barplot.legend(loc='upper right', ncol=2, fancybox=True, prop={'size': 12},title=plot_mode, labels=labels, title_fontsize=14)
barplot.spines['bottom'].set_color('0')
barplot.spines['top'].set_color('0')
barplot.spines['right'].set_color('0')
barplot.spines['left'].set_color('0')
#sns.despine(fig=None, top=True, right=True, left=True, bottom=False, offset=None, trim=False)
plt.xlabel('Genomes', fontsize=12)
plt.ylabel('Number of Elements', fontsize=12)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.show()
#plt.savefig(input_file+'.bar_plot.pdf',figsize=(3400,800),dpi=300, bbox_inches='tight')
plt.clf()